# Generated by Django 5.0 on 2024-06-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='days_of_week',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
