# Generated by Django 5.0 on 2024-06-26 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alarm_days_of_week_alter_alarm_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='alarm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
